### ISSUE TITLE
GTK: Search scrollback

### ISSUE THREAD

**Issue by mitchellh** [ghostty-org/ghostty#189]
A major missing feature is the ability to search scrollback, i.e. `cmd+f` on Mac, `ctrl+F` on Linux. 

This issue can be implemented in multiple steps, not just one giant PR:

- [x] Core, single-thread search functionality in `src/terminal` (#2885, #9585)
- [x] Search thread, mailbox on top of the core system utilizing the big renderer lock to read the screen for small time slices
- [x] Hook up the search thread to Surface
- [x] Rendering search matches in our renderers (non-GUI work)
- [x] Search iteration (prev/next match) #9702
- [x] Glue in apprt, bindings #9709 
- [x] macOS GUI #9709 
- [ ] GTK GUI

**EDIT:** There was a previous approach here (see edit history) with concurrent PageList access. After various false starts, I think I've identified a better path forward.

**Comment by GoldsteinE** [comment]
Prior art from foot: this dimming / highlighting looks really nice IMHO.

![Image](https://github.com/user-attachments/assets/8df7d2e7-98e5-46bc-974f-541f26778ad3)

**Comment by zzhaolei** [comment]
Using `cmd+shift+j` and `cmd+shift+alt+j` does not work. 
<img width="800" alt="Image" src="https://github.com/user-attachments/assets/ff90e307-8c94-4e0b-8076-02c4b755c082" />

**Comment by aofei** [comment]
OT: Genuinely think this issue should be pinned. 👀 (Been asked about this feature several times today)

**Comment by mitchellh** [comment]
> OT: Genuinely think this issue should be pinned. 👀 (Been asked about this feature several times today)

Good feedback. Pinned!

**Comment by weeheavy** [comment]
I'd love to see the elegance of Alacritty's search:
- `cmd`+`f` opens a small one-line search at the bottom
- `enter` scrolls foward through search results
- `shift`+`enter` scrolls backwards

**Comment by nervenes** [comment]
I'd like the UI for this to be native, similar to Terminal.app
<img width="682" alt="Image" src="https://github.com/user-attachments/assets/7f20352a-480d-4168-869b-f49eaf65bdb1" />

**Comment by sethgrid** [comment]
I just did a full grep of my file system looking for a breadcrumbs and then found out I can't search through my results. I was able to cmd+a cmd+c tab to vscode and cmd+p and then cmd+f. I am _constantly_ using cmd+f on my terminal :(

**Comment by econner** [comment]
Just noting here that for those of us wanting to try Ghostty out, but who are pretty dependent on this feature: we can pipe output from commands to a file and then use (in my case iTerm) to tail said file and still have cmd + f.

In Ghostty, `npm run dev 1>log.out 2>log.err &`
In iTerm, `tail -f log.out` or whatever

**Comment by AdrielVelazquez** [comment]
I wanted to provide some recipes for people waiting for this 

### Searching by piping to fzf

```
cat <ctri + shift + j> | fzf
cat /tmp/lxFj1l2gJE_1KUpyQWkPWQ/history.txt | fzf  (example command)
```

### Searching via Neovim 

Make sure that the default for xdg-open (linux) or open (mac) is set to nvim or whatever code editor you use

Example in NixOs
```
  xdg.mime.enable = true;
  xdg.mimeApps.enable = true;
  xdg.mimeApps.defaultApplications = {
    "text/plain" = [ "nvim.desktop" ];
  };
``` 

Then create a new keybinding in ghostty

```
keybind = ctrl+f=write_scrollback_file:open
```

### Using ZSH (Janky)

This is essentially just looking for the most recent history file. Sometimes the most recent output isn't there since it's dependent on calls to write_scrollback_file. And that's not a simple binary you can call. 

```
        function jank_scrollback_search() {
          # Find all files named history.txt in /tmp
          local files=$(find /tmp -name "history.txt" -print0 | xargs -0 stat -c '%Y %n' | sort -rn | head -n 1 | awk '{print $2}')

          # Check if any files were found
          if [[ -z "$files" ]]; then
            echo "No history.txt files found in /tmp" >&2
            return 1
          fi
          local trimmed_files=$(echo "$files" | tr -d ' \n')

          cat $trimmed_files | fzf
        }

        zle -N jank_scrollback_search

        # Bind the widget to Ctrl+f
        bindkey '^f' jank_scrollback_search
```

**Comment by elCarlosSantiago** [comment]
I've setup my new ghostty terminal and am really enjoying it. Unfortunately, wont be daily driving it until this functionality is ready. Key part of my workflow

**Comment by Tenzer** [comment]
To elaborate on the [earlier comment](https://github.com/ghostty-org/ghostty/issues/189#issuecomment-1824543708), a workaround for this currently exists in that you can bind keys to open an editor with all the text from the current terminal in it, which can then be searched through.

The default keybinds related to this are:
* `super+shift+j`: write_scrollback_file:paste
* `super+alt+shift+j`: write_scrollback_file:open

The documentation for `write_scrollback_file` can be found here: https://ghostty.org/docs/config/keybind/reference#write_scrollback_file.

One slight downside with these, as they are now, is that they only write contents outside the visible area to the temporary file, so they don't help if you want your search to also include what is currently shown.

If you want that included, you instead want to add a keybind that use the related [`write_screen_file`](https://ghostty.org/docs/config/keybind/reference#write_screen_file) method, as it includes all the contents in the tab.

I personally find `write_screen_file` more useful than `write_scrollback_file` so I have overridden the above mentioned keybinds to use that instead:
```
keybind = super+shift+j=write_screen_file:paste
keybind = super+alt+shift+j=write_screen_file:open
```

This allows me to press `super+alt+shift+j` which then opens the default editor for .txt files (at least on macOS) with the contents of the terminal, which can then be searched through.

**Comment by tednaleid** [comment]
for the workarounds, is there any way to script the calls to `write_scrollback_file` and `write_screen_file` or can they only be triggered via keybinds?

Currently, if I add this keybinding for writing the name of the screen file to the terminal:

```
keybind = super+shift+k=write_screen_file:paste
```

Then, I can manually type (on a Mac):

```
cat <cmd + shift + j> <cmd + shift + k> | fzf
```

If there were some way to trigger those actions without having to press the keybinding, I could do something like:

```
cat <(ghostty --run-action write_screen_file:paste) | fzf
```

and assign that to a script/alias

That'd give me almost all the scrollback searchability I need

**Comment by xzbdmw** [comment]
> and assign that to a script/alias

see https://github.com/ghostty-org/ghostty/discussions/3708#discussioncomment-11687205

**Comment by msharran** [comment]
I find [this](https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Browse-output-of-the-last-shell-command-in-pager) feature in kitty very useful. 

When my unit test output is very long, i just open the last command output in LESS and troubleshoot. 

If the cmd's output I am looking for is few prompts before, in kitty, I would navigate to it using keyboardd shortcuts (ghostty can also do this) and right click to open in LESS. 

In ghostty, it would be useful to redirect write_selection_file output to any program's STDIN. 

Like

```
keybind = "super+shift+w>s=write_selection_file | less"
```

**Comment by marianposaceanu** [comment]
Based on the previous comments - I'm currently using this on macOS:

```
keybind = super+f=write_screen_file:open
```

This way it won't stop me from using Ghostty as a daily driver.

**Comment by DontEatOreo** [comment]
I'm surprised `copy` isn't an option. Wouldn't this partially solve the issue since you can just quickly take a copy and go to another window and manually paste the path into your editor?

For example, right now, if you have a TUI program or you're in an interactive state, the only option you can use is `open`, since `paste` will cause an interaction

I'm personally rooting for https://github.com/ghostty-org/ghostty/issues/189#issuecomment-1624862463. This seems like one of the nicest implementations for such feature

Since this reply will ping a lot of people, I might as well just ask: Is there any workaround to still use open but to give it a custom program instead of it grabbing the default text editor?

**Comment by xzbdmw** [comment]
> I'm surprised copy isn't an option.

FYI you can use `cmd+a` + `cmd+c` to copy all the text.

**Comment by Stono** [comment]
> I've setup my new ghostty terminal and am really enjoying it. Unfortunately, wont be daily driving it until this functionality is ready. Key part of my workflow

Yeah I second this.  I've _really_ being enjoying Ghostty but found the inability to do cmd+f pretty debilitating in my day to day workflow. It's like the only missing piece of the puzzle for me!

**Comment by jdx** [comment]
this issue is the most thumbed several times over. There are likely hundreds of people subscribed to it. It's not helpful to post messages here simply saying it "doesn't fit your workflow". @mitchellh knows this is necessary. He'll work on it when he can I'm certain. Let's try to keep the discussion to helpful information.

**Comment by Stono** [comment]
Such rage.  I was actually complimenting the awesome terminal this is.  As the issue has been open for 18 months I made an assumption that it probably wasn't moving forward so was just adding my perspective to it.

I'm sorry you took such offence.

Merry Christmas!

**Comment by jdx** [comment]
I apologize if that came across as hostile, it was not meant to, nor what is it targeted at you since you're not the only one in recent days to have done this. My goal is simply to keep the discussion here helpful since it has a lot of eyeballs on it and we don't want to add to the noise.

**Comment by Stono** [comment]
That is completely fair, and I understand - thanks.  🤝

**Comment by martensson** [comment]
> > `keybind = super+f=write_screen_file:open`
> 
> Did anyone manage to get this to open in vim/nvim? I have nvim as my default editor on MacOS, but for some reason ghostty still opens the buffer in the default MacOS text edit.

It uses the default editor of MacOS, not your `$EDITOR`. There is an OS setting to modify it globally from the default (need to Google it), but probably better to change it to MacVim rather than a CLI-tool in this case.

**Comment by eaverdeja** [comment]
Thanks @martensson ! I got it to work with Neovide by setting the default editor via Launch Services:
```
 defaults write com.apple.LaunchServices/com.apple.launchservices.secure LSHandlers -array-add '{
    LSHandlerContentType = "public.plain-text";
    LSHandlerRoleAll = "com.neovide.neovide";
}'
```

**Comment by elCarlosSantiago** [comment]
> Thanks [@martensson](https://github.com/martensson) ! I got it to work with Neovide by setting the default editor via Launch Services:
> 
> ```
>  defaults write com.apple.LaunchServices/com.apple.launchservices.secure LSHandlers -array-add '{
>     LSHandlerContentType = "public.plain-text";
>     LSHandlerRoleAll = "com.neovide.neovide";
> }'
> ```

Great solution, officially daily driving it now. Here's the command for vscode, can be done for any editor.

```
{
    LSHandlerContentType = "public.plain-text";
    LSHandlerRoleAll = "com.microsoft.VSCode";
}

```

**Comment by justyn** [comment]
Regarding the implementation of search in Ghostty.

Different terminals have different approaches to search. For example, Wezterm has both [Copy Mode](https://wezfurlong.org/wezterm/copymode.html) and [Quick Select Mode](https://wezfurlong.org/wezterm/quickselect.html).

I personally would really value something that emulated my (Lazy)Vim configuration - not just basic Vim motions but custom textobjects, seeking with flash.nvim etc. Obviously I can get part of the way there with `write_selection_file` but it is a bit clunky and doesn't update with new output.

Given that it would be bloated for Ghostty implement all the different approaches, could it instead hand over to an external tool for the search? That would allow experimentation and innovation in this area without affecting Ghostty's code.

Perhaps there is something more streamlined than dumping the scrollback to a file then opening it in an editor... I haven't figured out the mechanics (a pointer? an emulated file?). Or is `write_scrollback_file` the only reasonable way it can be done?

**Comment by zxt-tzx** [comment]
> > Thanks [@martensson](https://github.com/martensson) ! I got it to work with Neovide by setting the default editor via Launch Services:
> > ```
> >  defaults write com.apple.LaunchServices/com.apple.launchservices.secure LSHandlers -array-add '{
> >     LSHandlerContentType = "public.plain-text";
> >     LSHandlerRoleAll = "com.neovide.neovide";
> > }'
> > ```
> 
> Great solution, officially daily driving it now. Here's the command for vscode, can be done for any editor.
> 
> ```
>  defaults write com.apple.LaunchServices/com.apple.launchservices.secure LSHandlers -array-add
> '{
>     LSHandlerContentType = "public.plain-text";
>     LSHandlerRoleAll = "com.microsoft.VSCode";
> }'
> ```

not sure if this applies more generally, but I needed to restart my Mac for this to take effect. thanks for the suggestion!

**Comment by github-cloud-cd** [comment]
On MacOS the `defaults` command requires you to log out and back in for it to take effect.  A reboot will also work.

**Comment by rmacklin** [comment]
> Regarding the implementation of search in Ghostty.
> 
> Different terminals have different approaches to search. For example, Wezterm has both [Copy Mode](https://wezfurlong.org/wezterm/copymode.html) and [Quick Select Mode](https://wezfurlong.org/wezterm/quickselect.html).

For quick select mode, there is a feature request here (about the analogous feature in kitty):
- https://github.com/ghostty-org/ghostty/discussions/2394

**Comment by Stono** [comment]
For some reason I couldn't get the commands above to work, but `duti` from `brew` helped:

```
brew install duti
duti -s com.microsoft.VSCode public.plain-text all
```

I didn't need to log back in for this either.

**Comment by mmerickel** [comment]
As a new user coming from iterm+tmux and trying to use ghostty as a replacement the main hangup I've run into is around scrollback management. With tmux I can use `ctrl-a-[` to enter a scrollback mode where I can use `?` and `/` to search the scrollback, as well as `hjkl` to navigate, `ctrl-u` to page up and `ctrl-d` to page down, and `space` to start a selection, and `enter` to finish a selection, copying it to the clipboard. I think something like this would require a new scope for key-bindings like `scrollback` alongside the current `all` and `global` scopes.

I would really love this modal capability in ghostty with the added benefit that whatever y'all do would also work well with the mouse where tmux tends to struggle.

**Comment by escluse** [comment]
> > Great solution, officially daily driving it now. Here's the command for vscode, can be done for any editor.
> > ```
> >  defaults write com.apple.LaunchServices/com.apple.launchservices.secure LSHandlers -array-add
> > '{
> >     LSHandlerContentType = "public.plain-text";
> >     LSHandlerRoleAll = "com.microsoft.VSCode";
> > }'
> > ```
> 
> not sure if this applies more generally, but I needed to restart my Mac for this to take effect. thanks for the suggestion!

You can do this using Finder: 

1/ select "Get Info" on any `.txt`, etc. file 
2/ change the "Open With" default to any macOS Application 

However, this doesn't work for `$EDITOR` and it's not worth creating a `.app` wrapper bundle given that it launches an entirely new instance.

**Comment by m4saurabh** [comment]
I like the way kitty does it, it exposes the scrollback buffer and you pipe that to any program, like less and more importantly neovim so you can move around with vim bindings without creating a subpar version of them.

**Comment by tmccombs** [comment]
FWIW, wezterm has a feature similar to kitty's which allows you to send the buffer to an external program. But also has  it's own search and navigation modes.

**Comment by leo-paz** [comment]
I just want this to work like warp :)

**Comment by m4saurabh** [comment]
@leo-paz you should share a video of it

**Comment by bofm** [comment]
iTerm highlights the searched pattern in live mode. This is handy when tailing some log and want to highlight something important but also not throw away the rest of the log as grep would do it.

**Comment by justyn** [comment]
> I like the way kitty does it, it exposes the scrollback buffer and you pipe that to any program, like less and more importantly neovim so you can move around with vim bindings without creating a subpar version of them.
> 

Thanks @m4saurabh for the hint on this Kitty functionality.

From there I also discovered [this incredible Neovim plugin](https://github.com/mikesmithgh/kitty-scrollback.nvim) which integrates with the Kitty scrollback buffer and provides some extra handy functionality.

[Here](https://youtu.be/9TINe0J9rNg?si=t7EBEulYxGdS8JZv&t=545) is part of a demo by the author (starting at 9:05) showing switching seamlessly between live Kitty and the scrollback buffer within Neovim. Note the little flash of the text redrawing but other than that you wouldn't know that you had left the terminal!

Most relevant to this discussion is that the author also details [here](https://youtu.be/9TINe0J9rNg?si=AuzvTN0bXiEe79Nx&t=290) (same video from 4:50) various approaches to getting the scrollback buffer into Neovim, starting with writing to a file then eventually settling on Kitty's built-in remote calls like [get-text](https://sw.kovidgoyal.net/kitty/generated/rc/#get-text).

It will be great if Ghostty can also allow for this kind of deep integration which offers the best of both worlds of native terminal and your raw custom Neovim power, plugins and all.

> But I suppose nothings speaks against also exposing the scrollback buffer for piping in addition to that.

I completely agree this kind of capability should be alongside rather than instead of built-in search.

In the meantime thanks to the great discussion in this thread I think I'm switching to Kitty for a while :-)

**Comment by joe-chandler** [comment]
> iTerm highlights the searched pattern in live mode. This is handy when tailing some log and want to highlight something important but also not throw away the rest of the log as grep would do it.

Indeed, with how much time i spend SSHd into servers, this feature pairs well with all of the other bazillions of utilities i have to use on live tailing of screaming logs. On OSX, i had to go back to iTerm2. Still using Ghostty on my personal laptop.

**Comment by quinncomendant** [comment]
Another use for scrollback search is to **highlight matching strings to make screenshots** that I send to colleagues. This is extra useful with regex search, to allow highlighting different types of strings. I use this often – here's an [example screenshot](https://send.strangecode.com/f/scr-20241220-qesf.png).

**Comment by withnale** [comment]
The ability to search scrollback and the ability to pipe scrollback to arbitrary commands are two different pieces of functionality. It would be nice to have both but this card is specifically about the former.

**Comment by CanRau** [comment]
> iTerm highlights the searched pattern in live mode. This is handy when tailing some log and want to highlight something important but also not throw away the rest of the log as grep would do it.

use(d) this all the time, currently trying to main ghostty tho 🤓 and hit the missing search feature pretty quickly 😅

**Comment by tuananh** [comment]
> Another use for scrollback search is to **highlight matching strings to make screenshots** that I send to colleagues. This is extra useful with regex search, to allow highlighting different types of strings. I use this often – here's an [example screenshot](https://send.strangecode.com/f/scr-20241220-qesf.png).

agreed. this is a very common use case.

**Comment by justyn** [comment]
> The ability to search scrollback and the ability to pipe scrollback to arbitrary commands are two different pieces of functionality. It would be nice to have both but this card is specifically about the former.

That's a good point. I've opened a discussion for a new feature request here: https://github.com/ghostty-org/ghostty/discussions/4870

**Comment by createchange** [comment]
For folks wanting to highlight and not lose surrounding context, follow output streams, etc. - you can take a look at `ack` (https://beyondgrep.com/).

<img width="448" alt="Image" src="https://github.com/user-attachments/assets/86d916fc-5b63-4b84-b0d7-ba8c2ece616a" />

**Comment by ollema** [comment]
> For folks wanting to highlight and not lose surrounding context, follow output streams, etc. - you can take a look at `ack` (https://beyondgrep.com/).
> 
> <img alt="Image" width="448" src="https://private-user-images.githubusercontent.com/29058450/401654199-86d916fc-5b63-4b84-b0d7-ba8c2ece616a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY1MTgzNDEsIm5iZiI6MTczNjUxODA0MSwicGF0aCI6Ii8yOTA1ODQ1MC80MDE2NTQxOTktODZkOTE2ZmMtNWI2My00Yjg0LWIwZDctYmE4YzJlY2U2MTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEwVDE0MDcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNWQwNjYwOTMxYjhhZGNiMjVmNGIxMDg0YWE5MDY5YzFkNDM5N2Q5ZTdkOTA1OGNhNDgyMmIxNTMxY2M1MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NZRGxTBgWcpVlZgrCcjtvJAJLIL1_ncHt_d51LiYEXk">

or just `rg --passthru` with [ripgrep](https://github.com/BurntSushi/ripgrep/tree/master)

**Comment by bofm** [comment]
> ack or ripgrep

Those are one-off. Can't re-search if the input it's saved.

**Comment by nachoal** [comment]
Any workarounds to cmd + f for searching for words in previous stdout that you can recommend for mac user?

**Comment by fxsalazar** [comment]
I use fzf:
`fzf < [cmd + shift + j]`

**Comment by mdeeks** [comment]
> Any workarounds to cmd + f for searching for words in previous stdout that you can recommend for mac user?

This config below opens your previous output and makes it searchable in your default text editor (I use Sublime). This has been working well for me. Though there seems to be a bug with write_scrollback_file so that it sometimes does not include the most recent lines in scrollback.

**cmd+f = Open your entire scrollback history in a text editor so you can search**

**cmd+shift+f = Open whatever you have selected in your scrollback history in a text editor**

```
# Search entire scrollback history in default text editor
keybind = cmd+f=write_scrollback_file:open

# Search Selection
# HOWTO: Cmd+triple_click to select your last output then press cmd+shift+f to search it
keybind = cmd+shift+f=write_selection_file:open

# RECOMMENDED: Set this to something big so you can capture all of your scrollback
scrollback-limit = 20000000

# How to change your system-wide default text editor to Sublime
# brew install duti
# duti -s com.sublimetext.4 public.plain-text all
```

**Comment by pioz** [comment]
Is there an ETA for this feature by any chance?

**Comment by andoniabedul** [comment]
> Is there an ETA for this feature by any chance?

@pioz the ETA is the time that you can fix the bug by yourself; if you don't know how, wait with patient without asking when it will be ready. :) this is an open source terminal without no remuneration. Sorry for the hard response btw.

**Comment by pioz** [comment]
> > Is there an ETA for this feature by any chance?
> 
> [@pioz](https://github.com/pioz) the ETA is the time that you can fix the bug by yourself; if you don't know how, wait with patient without asking when it will be ready. :) this is an open source terminal with no remuneration. Sorry for the hard response btw.

@andoniabedul Yes, absolutely, I completely agree with you. I only asked to check if there might be any updates, as this feature is quite important to me. Let’s say that a simple "there's no ETA currently" might have come across as a bit kinder, but it's all good nonetheless. Thanks for the information!

**Comment by RoyTinker** [comment]
I have loved using Ghostty for the last several weeks, but the lack of scrollback searching is forcing me back to iTerm2. Hope to be back soon! :)

**Comment by coltnz** [comment]
The good enough workaround is : https://github.com/ghostty-org/ghostty/issues/189#issuecomment-2564719973

**Comment by exsesx** [comment]
> The good enough workaround is : [#189 (comment)](https://github.com/ghostty-org/ghostty/issues/189#issuecomment-2564719973)

I haven’t explored this workaround in depth yet, but using `write_screen_file:open` on macOS opens the `TextEdit` app instead of `nvim` in Ghostty. While `TextEdit` could work, I’d prefer to wait for this feature to be implemented directly in Ghostty. I’m open to configuring it further, but for now, it doesn’t feel very user-friendly. Thanks for sharing the workaround, though!

**Comment by evandam** [comment]
Agreed, I think opening it with `$PAGER` would make for a pretty good user experience if it's possible until a more native scroll bar.

**Comment by sassanh** [comment]
Do we need native pagination at all? Why should each terminal emulator implement its own pagination, scrollback, search, etc., with its own design preferences? We already have lots of pagination tools like less, more, bat, pg, most, etc., and lots of editors that have view mode like vim, emacs, neovim, etc.

Personally, I would rather press a key combination and see my scrollback opened in my neovim with all my plugins, in which I have full control over the content, and the key bindings are all already in my muscle memory. That's what I was doing in Kitty for years.

If one prefers another pagination tool, they can open it in that tool, and we don't need to re-implement a semi-vim or semi-emacs for this purpose.

One could set it in the configuration, and it can use `$PAGER` by default. If `$PAGER` is not provided, it will default to `less`.

**Comment by Crocmagnon** [comment]
> I would rather press a key combination and see my scrollback opened in my neovim

That’s your preference, and it’s fine. But there are others who prefer having a native search feature. That doesn’t prevent your workflow from still working, it’s just another option.

**Comment by haseeb-heaven** [comment]
> Based on the previous comments - I'm currently using this on macOS:
> 
> ```
> keybind = super+f=write_screen_file:open
> ```
> 
> This way it won't stop me from using Ghostty as a daily driver.

This only opened output into Text editor, This is a **hack** not actual feature we wanted

**Comment by ttilberg** [comment]
Opening the scrollback buffer hasn't worked well for me, as most of the time when I'm wanting to search for specific output, it's during a running process, such as a Rails server, or Scrapy run. It adds a more dissonance to the process. I kept getting burned in situations where it was hard or impossible to reasonably check something compared to iTerm and had to switch back for now.

I hate to ask for features in an open source project; it would be cool if there was a feature bounty or something. I'd put a tip in the tip jar for this. Let me know if there's somewhere I can put some money where my mouth is; perhaps others would follow.

**Comment by e-kotov** [comment]
> it would be cool if there was a feature bounty or something. I'd put a tip in the tip jar for this. Let me know if there's somewhere I can put some money where my mouth is; perhaps others would follow.

good point, I would join.

**Comment by gorkunov** [comment]
You may not realize it, but this is primarily the work of one incredible individual. Mitchell likely has enough financial security for the rest of his life and even for his children’s future (I believe).

Unfortunately, this means we can’t motivate him to take action simply by offering to pay for it. At this point, it’s all about time and priorities, and unless Mitchell finds someone else willing and able to take on this work, progress may remain limited.

**Comment by blacktop** [comment]
Mitchell is very aware of the importance of this feature and will solve it in a perfectly appropriate way that fits in with his ghostty design language and UX. He's focusing on stability and bug fixes for v1.1 and then will focus on this possibly for the version following that. Nothing left for us to do except be patient or open a PR ;)

**Comment by AdrielVelazquez** [comment]
This is the PR--which should definitely not be used--of how I'm getting around it for now. 

I essentially added a new option to `WriteScreenAction` which will open up the scrollback in your defined `$EDITOR` so that it stays within the terminal. 

This is doesn't fully leverage the way that ghostty or termio expect you to launch this command, but it was more me getting familiar with the codebase in general. 

[PR New Write Screen Action](https://github.com/AdrielVelazquez/ghostty/pull/2)

This allows the new keybind of ctrl + shift + f to open the scrollback in whatever you use as `$EDITOR`

**Comment by jamesharr** [comment]
Specific designs aside, the big 2 use cases I have:
1. searching for something in my scrollback.
2. highlighting all instances of a specific field. As mentioned above, searching for "FAIL" or "ERROR" is probably a common, but it depends on what I'm doing.
   - Sometimes I might want to highlight a specific log term, so using a static configuration might not be appropriate.
   - I also wind up glancing at the scrollbar to look for when terms may have scrolled by

It's possible that these are better as separate actions/features, but that's how I use it today. Sometimes I want to find go something, sometimes I just want to draw my attention to certain strings while I run other stuff.

**Comment by frejonb** [comment]
This issue has multiple workarounds for this functionality but I'm genuinely interested in how @mitchellh's workflow looks like to not need this functionality (based on the previous reply):

> I originally considered this a blocker for 1.0 but the reality is that we ended the beta with almost 5,000 testers and the vast, vast majority found Ghostty productive and perfectly usable without this feature (me included, using it daily for 2 years!). So, I'm not downplaying the importance of this issue but I think it's okay to ship 1.0 without this and add it after.

**Comment by jcollie** [comment]
I don't know what Mitchell's workflow is, but since the dawn on time when TTYs stopped recording everything on paper we've gotten by just fine with tools like `tee`, `more`, and more recently `less`.

**Comment by martensson** [comment]
> I don't know what Mitchell's workflow is, but since the dawn of time when TTYs stopped recording everything on paper we've gotten by just fine with tools like `tee`, `more`, and more recently `less`.

While I partly agree and often use `grep`, `ripgrep`, `less`, `vim -`, etc., it is not always feasible. Not all applications quit with an output that can be piped to another tool to search certain keywords. Sometimes I just forget before running a command, and need then to run it again to parse the output (and that is not always possible, and some commands can take minutes to run). Other times the output is just unpredictable and I need see it before searching.

And in my case I often benefit from the context and update my search patterns live while scrolling. These are some of the cases where terminal search is super useful, and something I use daily working as an SRE where I spend a lot of time reading logs and app outputs. It is also the reason I personally switch back and forth between Ghostty and iterm2, and the only thing keeping me back from doing a full switch.

**Comment by hayesgm** [comment]
Curious on using `cmd+shift+j` or `keybind = ctrl+f=write_scrollback_file:open`, can either of these retain ANSI control codes? It feels hard to lose colors when exploring large scrollbacks.

**Comment by gregopet** [comment]
>  where I spend a lot of time reading logs and app outputs.

Exactly - it's the case where you find data X in the output, correlate it with Y and eventually end up at Z. You don't want to rerun your whole activity for that and it's great not to have to think about these things beforehand (oh no, I noticed a weird bug but I wasn't piping my output to less 😱 )

**Comment by trashhalo** [comment]
For my own workflow ive been managing to get by using `>` to dump long outputs into a file then nvim that file.

```bash
run_chatty_thing > tmp.log
nvim tmp.log
```

**Comment by Syphdias** [comment]
**Please stop suggesting workarounds.** There are enough of it in this thread. I believe there are situations where theses workarounds (`|less`, `tee`/`>`, etc.) don'te work but I won't mention them to not trigger a response that there is in fact a workaround.

The only things I — and potentially other subscribers to this issue — am interested in this issue are contributions regarding the resolution. 

I would suggest closing the issue to discussion.

/rant over, sorry

**Comment by dancrossnyc** [comment]
I anxiously await this feature; it would be super cool if one could search for regular expressions, as well. It's such a Unix-y thing, but shockingly absent from so many tools.

**Comment by jcollie** [comment]
Sorry, but I'm locking this conversation. There's hasn't been any productive conversation on this issue for a very long time. We won't forget about this feature, it's just not on the immediate roadmap.

**Comment by mitchellh** [comment]
To be completely clear, it’s not on the “IMMEDIATE” roadmap (as noted in the prior comment). It’s absolutely on the roadmap and I even already started some it in a branch. But as a passion project, we prioritize working on whatever we want and this isn’t currently the priority. It’s high on the list but not like.. next release (“immediate”) priority at the time of this comment. 

This issue was closed because the comments haven’t been productive towards completing this. 

I outlined some suggestions for how this can be incrementally contributed. If someone comes along and implements this I’d be happy to take a look and probably speed up merging.

Otherwise, if you aren’t doing the work, please respect the other volunteers on this project and be patient. We’ll get it it when we want. If this is a blocker for you, you can and should use another terminal. There are fantastic choices out there!

**Comment by mitchellh** [comment]
New progress, new direction: #9585 Still a ways to go but this is a big leap forward towards making search functional. The PR description outlines a new path forward, too that invalidates the original TODO list in this issue (I'm updating that now).

**Comment by mitchellh** [comment]
#9687 It's coming along.

https://github.com/user-attachments/assets/80b1c672-60d2-4321-884d-8a048527a3f4

**Comment by mitchellh** [comment]
#9702 search results are now navigable with keybinds. GUI next.

https://github.com/user-attachments/assets/7887796c-ea9b-44c4-b24c-414eb7d58000

**Comment by mitchellh** [comment]
#9709 macOS GUI. A couple known issues and TODOs to address but this issue is almost resolved for macOS.

https://github.com/user-attachments/assets/79f4b2ad-70ef-4b09-a8a2-b21441dd15da

**Comment by mitchellh** [comment]
macOS tip releases now have search.

**Comment by mitchellh** [comment]
Changed the title and labels, this is now a GTK only issue.

**Comment by mitchellh** [comment]
GTK UI: #9756
