### ISSUE TITLE
Inspector Improvements Tracking Issue

### ISSUE THREAD

**Issue by mitchellh** [ghostty-org/ghostty#814]
This is a tracking issue for multiple improvements that can be made to the inspector. If you start working on any of these, feel free to open a new dedicated issue for the task. Otherwise, we can use this as a holding ground for future work.

**A lot of these are very contributor friendly. This is a great place to start hacking on Ghostty if you're interested.**

- [ ] macos: support opening the inspector in a pop-up window (as Linux does now)
- [ ] macos: support opening the inspector in a horizontal split
- [ ] macos: support opening in a split by extending the window instead of shrinking the terminal
- [ ] macos: scrolling with touchpad is too fast (https://github.com/ghostty-org/ghostty/issues/1375)
- [ ] linux/macos: support monitor DPI for font scaling
- [ ] add ability to change font family and size (#1097, #1095)
- [ ] list traversal (i.e. in Terminal IO tab) should support arrow keys (#1096)
- [ ] add copy to clipboard button for terminal IO (#1092)
- [ ] add semantic prompt row flags to the inspector
- [ ] add visual indicator of some sort to show what terminal an inspector is associated with (#1386)
- [ ] show termios configuration (#2587)
- [ ] show indication that echo is off for keyboard input (#2587)

**Comment by bartgrantham** [comment]
minor inspector UI suggestion (macOS, maybe others): show a checkmark next to "Terminal Inspector" under the View menu if the inspector is currently open.  This provides feedback for users who open the inspector for the first time and are looking how to close it.  Alternatively or in addition, change the menu item to "Toggle Terminal Inspector".

**Comment by jcollie** [comment]
@bartgrantham please don't revive such old issues (that should have been closed long ago). Please open a new discussion with your suggestion.
